theme: jekyll-theme-minimal
show_downloads: false
title: The Photographers Field Guide to Beijing
description: Photographers really need better info for their trip to China. So that you can focus on getting the shot, I wrote The Photographers Field Guide to Beijing. Read extra chapters from the book here.
author: Zach McCabe
social:
  name: Zach McCabe
  links:
    - https://amazon.com/author/zachmccabe
